#!/bin/bash
echo ">>>>start to init slave"
set +e
#ls no-exit-file
#whoami
# 查看主服务器的状态
MASTER_STATUS=$(MYSQL_PWD=${MYSQL_ROOT_PASSWORD} mysql -u root -h '172.25.0.201' -e "show master status\G")
echo "MASTER_STATUS:${MASTER_STATUS}"
# binlog文件名字,对应 File 字段,值如: mysql-bin.000004
MASTER_LOG_FILE=$(echo "${MASTER_STATUS}" | awk 'NR!=1 && $1=="File:" {print $2}')
echo "MASTER_LOG_FILE:${MASTER_LOG_FILE}"
# binlog位置,对应 Position 字段,值如: 1429
MASTER_LOG_POS=$(echo "${MASTER_STATUS}" | awk 'NR!=1 && $1=="Position:" {print $2}')
echo "MASTER_LOG_POS:${MASTER_LOG_POS}"
# 设置主节点的信息
MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql -u root -e "CREATE USER '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}'; GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}'; CHANGE MASTER TO MASTER_HOST='172.25.0.201', MASTER_USER='${MYSQL_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}', MASTER_LOG_FILE='${MASTER_LOG_FILE}', MASTER_LOG_POS=${MASTER_LOG_POS}; START SLAVE;" >> ./temp.log 2>&1
#MYSQL_PWD=${MYSQL_ROOT_PASSWORD} mysql -u root -e "GRANT ALL ON *.* TO '${MYSQL_REPLICATION_USER}'@'172.25.0.204' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}'"
MYSQL_EXECUTE=$(cat ./temp.log)
echo "MYSQL_EXECUTE:${MYSQL_EXECUTE}"
MYSQL_EXECUTE_STATUE=$(echo "${MYSQL_EXECUTE}" | awk '{print $1}')
echo "MYSQL_EXECUTE_STATUE:${MYSQL_EXECUTE_STATUE}"
# 如果设置主节点失败，重新设置
if [ "${MYSQL_EXECUTE_STATUE}" = "ERROR" ]; then
  echo "MYSQL_EXECUTE_STATUE:${MYSQL_EXECUTE_STATUE}"
  MYSQL_PWD=${MYSQL_ROOT_PASSWORD} mysql -u root -e "STOP SLAVE FOR CHANNEL ''; RESET SLAVE; CHANGE MASTER TO MASTER_HOST='172.25.0.201', MASTER_USER='${MYSQL_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}', MASTER_LOG_FILE='${MASTER_LOG_FILE}', MASTER_LOG_POS=${MASTER_LOG_POS}; START SLAVE;"
fi